### ISSUE TITLE
maven 包 dubbo-registry-kubernetes 是这个项目么?

### ISSUE THREAD

**Issue by liuzhiguo630** [apache/dubbo-kubernetes#10]
我想试用 dubbo、kubernetes 相关功能，发现所有的 sample 都引用了 dubbo-registry-kubernetes 这个包，但该包在 dubbo 的主页上没有任何打包记录。在任何 sample 中都没有提到 dubbo-registry-kubernetes 项目，但是所有人都用到了，缺了该项目根本就起不来。

**版本不一致**
每个 sample 的版本也不尽一致，有的是 3.0.1-SNAPHOT，有的是 3.0.2 。

在 https://mvnrepository.com/artifact/org.apache.dubbo/dubbo-registry-kubernetes 上，这个包已经到 3.0.5 了，怎么打包上去的？为什么在本项目看不到 Release 记录？如果这个包是本项目的话，为什么没有代码提交记录？

**Comment by AlbumenJ** [comment]
和 Kubernetes 的适配会在 3.1 版本提供完整支持，此仓库已经废弃

**Comment by GoldSubmarine** [comment]
请问 3.1 预计何时发布呀？ @AlbumenJ

**Comment by AlbumenJ** [comment]
8月中旬发布
