### ISSUE TITLE
挖坑挖到一半不填，害人

### ISSUE THREAD

**Issue by geoleonsh** [apache/dubbo-kubernetes#3]
这个坑挖得，连很多基本的功能都跑不通，就放上来了，也不维护，直接删repository不行吗？

**Comment by leechor** [comment]
> 这个坑挖得，连很多基本的功能都跑不通，就放上来了，也不维护，直接删repository不行吗？

阿里特色

**Comment by kimmking** [comment]
https://dubbo.apache.org/zh-cn/blog/dubbo-k8s.html

**Comment by chickenlj** [comment]
这个子工程是社区参与者对于 dubbo 适配 kubernetes 基础设施的探索，可以多关注 dubbo 3.0 的后续规划，后续应该会对这部分有全新的思考和支持。

**Comment by crazyStar00** [comment]
> https://dubbo.apache.org/zh-cn/blog/dubbo-k8s.html

打不开了。

**Comment by AlbumenJ** [comment]
> > https://dubbo.apache.org/zh-cn/blog/dubbo-k8s.html
> 
> 打不开了。

You can refer this in https://github.com/apache/dubbo-website/blob/master/content/zh/blog/news/dubbo-k8s.md.

Also, the new implement for kubernetes will be introduced in [Dubbo 3.0](https://github.com/apache/dubbo/tree/3.0/dubbo-registry/dubbo-registry-kubernetes).
