### ISSUE TITLE
dubboctl can not run standalone

### ISSUE THREAD

**Issue by 2456868764** [apache/dubbo-kubernetes#55]
### Steps to reproduce this issue

1. git clone https://github.com/apache/dubbo-kubernetes.git 
2. cd app/dubboctl 
3. go build -o dubboctl main.go
4. mv ./dubboctl ~/Downloads
5.  rm -f -R  dubbo-kubernetes （project directory）
6. ~/Downloads/dubboctl profile list

```
Error: open /Users/jun/java/dubbo/dubbo-kubernetes/deploy/profiles: no such file or directory

```

7.   app/dubboctl/identifier/env.go

```
var (
	_, b, _, _ = runtime.Caller(0)
	// Root folder of dubbo-admin
	// This relies on the fact this file is 3 levels up from the root; if this changes, adjust the path below
	Root            = filepath.Join(filepath.Dir(b), "../../..")
	Deploy          = filepath.Join(Root, "/deploy")
	Charts          = filepath.Join(Deploy, "/charts")
	Profiles        = filepath.Join(Deploy, "profiles")
	Addons          = filepath.Join(Deploy, "addons")
	AddonDashboards = filepath.Join(Addons, "dashboards")
	AddonManifests  = filepath.Join(Addons, "manifests")
)

```

The Root value is project source code directory when is build, so dubboctl can not run standalone.

**Comment by chickenlj** [comment]
This issue should be addressed when preparing for the release packages #51
