### ISSUE TITLE
Front-end packaging issues

### ISSUE THREAD

**Issue by sjmshsh** [apache/dubbo-kubernetes#56]
There is a problem with the path of index.html generated after the current-end UI is packaged, causing the resource to not be found.
<script defer="defer" src="/static/js/chunk-vendors.6ea1db8a.js"></script><script defer="defer" src="/static/js/app.13889972.js"></script><lin    k href="/static/css/chunk-vendors.90cf4675.css" rel="stylesheet"><link href="/static/css/app.4ab00ae8.css" rel="stylesheet"></head><body><div id="app"></div></body></html>      /static in this place should be static         

.
├── dubbo-admin-info.json
├── dubbo.ico
├── echarts-en.min.js
├── fonts
│   ├── flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2
│   ├── KFOlCnqEu92Fr1MmEU9fABc4AMP6lbBP.woff2
│   ├── KFOlCnqEu92Fr1MmEU9fBBc4AMP6lQ.woff2
│   ├── KFOlCnqEu92Fr1MmEU9fBxc4AMP6lbBP.woff2
│   ├── KFOlCnqEu92Fr1MmEU9fCBc4AMP6lbBP.woff2
│   ├── KFOlCnqEu92Fr1MmEU9fChc4AMP6lbBP.woff2
│   ├── KFOlCnqEu92Fr1MmEU9fCRc4AMP6lbBP.woff2
│   ├── KFOlCnqEu92Fr1MmEU9fCxc4AMP6lbBP.woff2
│   ├── KFOlCnqEu92Fr1MmSU5fABc4AMP6lbBP.woff2
│   ├── KFOlCnqEu92Fr1MmSU5fBBc4AMP6lQ.woff2
│   ├── KFOlCnqEu92Fr1MmSU5fBxc4AMP6lbBP.woff2
│   ├── KFOlCnqEu92Fr1MmSU5fCBc4AMP6lbBP.woff2
│   ├── KFOlCnqEu92Fr1MmSU5fChc4AMP6lbBP.woff2
│   ├── KFOlCnqEu92Fr1MmSU5fCRc4AMP6lbBP.woff2
│   ├── KFOlCnqEu92Fr1MmSU5fCxc4AMP6lbBP.woff2
│   ├── KFOlCnqEu92Fr1MmWUlfABc4AMP6lbBP.woff2
│   ├── KFOlCnqEu92Fr1MmWUlfBBc4AMP6lQ.woff2
│   ├── KFOlCnqEu92Fr1MmWUlfBxc4AMP6lbBP.woff2
│   ├── KFOlCnqEu92Fr1MmWUlfCBc4AMP6lbBP.woff2
│   ├── KFOlCnqEu92Fr1MmWUlfChc4AMP6lbBP.woff2
│   ├── KFOlCnqEu92Fr1MmWUlfCRc4AMP6lbBP.woff2
│   ├── KFOlCnqEu92Fr1MmWUlfCxc4AMP6lbBP.woff2
│   ├── KFOmCnqEu92Fr1Mu4mxKKTU1Kg.woff2
│   ├── KFOmCnqEu92Fr1Mu4WxKKTU1Kvnz.woff2
│   ├── KFOmCnqEu92Fr1Mu5mxKKTU1Kvnz.woff2
│   ├── KFOmCnqEu92Fr1Mu72xKKTU1Kvnz.woff2
│   ├── KFOmCnqEu92Fr1Mu7GxKKTU1Kvnz.woff2
│   ├── KFOmCnqEu92Fr1Mu7mxKKTU1Kvnz.woff2
│   └── KFOmCnqEu92Fr1Mu7WxKKTU1Kvnz.woff2
├── html
│   ├── 50x.html
│   ├── dubbo-admin-info.json
│   ├── dubbo.ico
│   ├── echarts-en.min.js
│   ├── fonts
│   │   ├── flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2
│   │   ├── KFOlCnqEu92Fr1MmEU9fABc4AMP6lbBP.woff2
│   │   ├── KFOlCnqEu92Fr1MmEU9fBBc4AMP6lQ.woff2
│   │   ├── KFOlCnqEu92Fr1MmEU9fBxc4AMP6lbBP.woff2
│   │   ├── KFOlCnqEu92Fr1MmEU9fCBc4AMP6lbBP.woff2
│   │   ├── KFOlCnqEu92Fr1MmEU9fChc4AMP6lbBP.woff2
│   │   ├── KFOlCnqEu92Fr1MmEU9fCRc4AMP6lbBP.woff2
│   │   ├── KFOlCnqEu92Fr1MmEU9fCxc4AMP6lbBP.woff2
│   │   ├── KFOlCnqEu92Fr1MmSU5fABc4AMP6lbBP.woff2
│   │   ├── KFOlCnqEu92Fr1MmSU5fBBc4AMP6lQ.woff2
│   │   ├── KFOlCnqEu92Fr1MmSU5fBxc4AMP6lbBP.woff2
│   │   ├── KFOlCnqEu92Fr1MmSU5fCBc4AMP6lbBP.woff2
│   │   ├── KFOlCnqEu92Fr1MmSU5fChc4AMP6lbBP.woff2
│   │   ├── KFOlCnqEu92Fr1MmSU5fCRc4AMP6lbBP.woff2
│   │   ├── KFOlCnqEu92Fr1MmSU5fCxc4AMP6lbBP.woff2
│   │   ├── KFOlCnqEu92Fr1MmWUlfABc4AMP6lbBP.woff2
│   │   ├── KFOlCnqEu92Fr1MmWUlfBBc4AMP6lQ.woff2
│   │   ├── KFOlCnqEu92Fr1MmWUlfBxc4AMP6lbBP.woff2
│   │   ├── KFOlCnqEu92Fr1MmWUlfCBc4AMP6lbBP.woff2
│   │   ├── KFOlCnqEu92Fr1MmWUlfChc4AMP6lbBP.woff2
│   │   ├── KFOlCnqEu92Fr1MmWUlfCRc4AMP6lbBP.woff2
│   │   ├── KFOlCnqEu92Fr1MmWUlfCxc4AMP6lbBP.woff2
│   │   ├── KFOmCnqEu92Fr1Mu4mxKKTU1Kg.woff2
│   │   ├── KFOmCnqEu92Fr1Mu4WxKKTU1Kvnz.woff2
│   │   ├── KFOmCnqEu92Fr1Mu5mxKKTU1Kvnz.woff2
│   │   ├── KFOmCnqEu92Fr1Mu72xKKTU1Kvnz.woff2
│   │   ├── KFOmCnqEu92Fr1Mu7GxKKTU1Kvnz.woff2
│   │   ├── KFOmCnqEu92Fr1Mu7mxKKTU1Kvnz.woff2
│   │   └── KFOmCnqEu92Fr1Mu7WxKKTU1Kvnz.woff2
│   ├── index.html
│   ├── OpenSans.css
│   └── static
│       ├── css
│       │   ├── app.4ab00ae8.css
│       │   ├── app.888953a3.css
│       │   ├── app.f8af26eb.css
│       │   ├── chunk-vendors.15048f58.css
│       │   ├── chunk-vendors.90cf4675.css
│       │   └── chunk-vendors.ad39ed5a.css
│       ├── img
│       │   ├── jsoneditor-icons.94cc3007.svg
│       │   └── max_btn.546521f3.svg
│       └── js
│           ├── app.13889972.js
│           ├── app.13889972.js.map
│           ├── braceBase.26ea46f8.js
│           ├── braceBase.26ea46f8.js.map
│           ├── chunk-vendors.6ea1db8a.js
│           └── chunk-vendors.6ea1db8a.js.map
├── index.html
├── OpenSans.css
└── static
    ├── css
    │   ├── app.4ab00ae8.css
    │   └── chunk-vendors.90cf4675.css
    ├── img
    │   ├── jsoneditor-icons.94cc3007.svg
    │   └── max_btn.546521f3.svg
    └── js
        ├── app.13889972.js
        ├── app.13889972.js.map
        ├── braceBase.26ea46f8.js
        ├── braceBase.26ea46f8.js.map
        ├── chunk-vendors.6ea1db8a.js
        └── chunk-vendors.6ea1db8a.js.map

**Comment by chickenlj** [comment]
![image](https://github.com/apache/dubbo-kubernetes/assets/18097545/9a4d3f71-d1b0-4aa4-9715-fb148630e52d)
