### ISSUE TITLE
Upgrade to Vue 3 in the UI project .

### ISSUE THREAD

**Issue by Helltab** [apache/dubbo-kubernetes#76]
- [x] I have searched the [issues](https://github.com/apache/dubbo-kubernetes/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [REAMDE](https://github.com/apache/dubbo-kubernetes/blob/master/README.md) of this repository and believe that this is not a duplicate.

### Environment

* dubbo-admin-ui: 0.3.0-SNAPSHOT

### Steps to reproduce this issue

1. upgrade vue2.6 to ^3.3.4
2. use ui with antdv ^4.0.7

### Expected Result
The Vue 3 framework offers improved performance compared to Vue 2.6, resulting in higher efficiency for our UI project.

**Comment by chickenlj** [comment]
Could you please file a pull request for this?
