### ISSUE TITLE
Define the core caching or adapting layer for dubbo-cp to support both universal and kubernetes mode 

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo-kubernetes#78]
We should define an caching or adapting layer for dubbo-cp console to work with both Universal and Kubernetes mode, it should be able to:
1. Hide the implementation details of Zookeeper/Nacos or Kubernetes server.
2. Provide unified API for different dubbo-cp console features.

Reference implementations we have now:
1. Dubbo-cp, Universal cache implementation in  https://github.com/apache/dubbo-kubernetes/tree/master/pkg/admin/cache
3. Kiali, Kubernetes/Mesh cache implementation in https://github.com/kiali/kiali/tree/master/kubernetes
4. Kuma, the Universal and Kubernetess mode in https://github.com/kumahq/kuma

**Comment by ev1lQuark** [comment]
Work in progress.
