### ISSUE TITLE
Github action for automatically building `ui` and submit to `app/dubbo-ui` on frontend resources update

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo-kubernetes#97]

**Comment by yin1999** [comment]
I'd like to take this.

Here are my thoughts:

Create a workflow that is triggered when there is new commit to the main branch and the front-end related code is modified. It will compile the front-end code and if the build asset is different with the on in main branch, a PR will be automatically created to update the build asset under the `app/dubbo-ui` folder. Members with write access to this repo can merge the build into the main branch.
